http:
    addr: ":8080"
    username: admin
    password: cheese
    chartPath: "charts"

storage:
    enabled: true
    bucket_url: "s3://nsl-artifacts"

cache:
    base_dir: "/tmp"

repositories:
    - url: "https://repo1.maven.org/maven2"
    - url: "http://uk.maven.org/maven2/"
