name: Lint

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Check out code
        uses: actions/checkout@v2

      - name: Lint
        run: make all
        env:
          GOPATH: /home/runner/work/bucketrepo/bucketrepo/go

